-- Create the weather_searches table for search history
CREATE TABLE IF NOT EXISTS weather_searches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  city TEXT NOT NULL,
  country TEXT,
  temperature INTEGER,
  condition TEXT,
  humidity INTEGER,
  wind_speed INTEGER,
  icon TEXT,
  searched_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE weather_searches ENABLE ROW LEVEL SECURITY;

-- Allow anonymous insert
CREATE POLICY "Allow anonymous insert" ON weather_searches
  FOR INSERT TO anon
  WITH CHECK (true);

-- Allow anonymous select
CREATE POLICY "Allow anonymous select" ON weather_searches
  FOR SELECT TO anon
  USING (true);

-- Allow anonymous delete
CREATE POLICY "Allow anonymous delete" ON weather_searches
  FOR DELETE TO anon
  USING (true);
